version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - base
      - redis
    links:
      - base
      - redis
  redis:
    image: "redis:alpine"
  base:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
